### PR TITLE
Add Docker support with example `docker-compose.yml`.

### PR DESCRIPTION
**Pull request by jasmeralia**
I had to downgrade `numpy` as there was some real weirdness going on with 2.0.0.

### CODE REVIEW

**Comment by jasmeralia** [comment]
I can add a GitHub Action to auto-publish to GHCR if you want, but you'll need to adjust the permissions on the repo to allow the GHA to work.

**Comment by Bombg** [comment]
What permissions need to be adjusted?

**Comment by jasmeralia** [comment]
Under Actions > General, the workflow would need read and write:

**Comment by Bombg** [comment]
looks like it's set that way by default, but I saved it just in case.

**Review by Bombg — APPROVED** [review]

**Pull request merged**
